// Package capability provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package capability

// Adapters Service mesh adapter visibility settings.
type Adapters struct {
	AppMesh *bool `json:"appMesh,omitempty" yaml:"appMesh,omitempty"`
	Cilium  *bool `json:"cilium,omitempty" yaml:"cilium,omitempty"`
	Citrix  *bool `json:"citrix,omitempty" yaml:"citrix,omitempty"`
	Consul  *bool `json:"consul,omitempty" yaml:"consul,omitempty"`
	Istio   *bool `json:"istio,omitempty" yaml:"istio,omitempty"`
	Kuma    *bool `json:"kuma,omitempty" yaml:"kuma,omitempty"`
	Linkerd *bool `json:"linkerd,omitempty" yaml:"linkerd,omitempty"`
	Nginx   *bool `json:"nginx,omitempty" yaml:"nginx,omitempty"`
	Nsm     *bool `json:"nsm,omitempty" yaml:"nsm,omitempty"`
}

// Capability Provider capability configuration returned to Meshery on handshake.
type Capability struct {
	// ProviderType Type of the provider (e.g. "remote").
	ProviderType *string `json:"providerType,omitempty" yaml:"providerType,omitempty"`

	// PackageVersion Version of the provider package.
	PackageVersion *string `json:"packageVersion,omitempty" yaml:"packageVersion,omitempty"`

	// PackageUrl URL from which the provider package can be downloaded.
	PackageUrl *string `json:"packageUrl,omitempty" yaml:"packageUrl,omitempty"`

	// ProviderName Display name of the provider.
	ProviderName *string `json:"providerName,omitempty" yaml:"providerName,omitempty"`

	// ProviderDescription List of human-readable description lines for the provider.
	ProviderDescription *[]string `json:"providerDescription,omitempty" yaml:"providerDescription,omitempty"`

	// Extensions Extension points for the Meshery UI and backend.
	Extensions *struct {
		Navigator *[]struct {
			AllowedTo *map[string]interface{} `json:"allowedTo,omitempty" yaml:"allowedTo,omitempty"`
			Component *string                 `json:"component,omitempty" yaml:"component,omitempty"`

			// Href Href configuration for navigator extensions.
			Href *struct {
				External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
				Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
			} `json:"href,omitempty" yaml:"href,omitempty"`
			Icon            *string `json:"icon,omitempty" yaml:"icon,omitempty"`
			IsBeta          *bool   `json:"isBeta,omitempty" yaml:"isBeta,omitempty"`
			Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
			OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
			Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
			Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
			Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
		} `json:"navigator,omitempty" yaml:"navigator,omitempty"`
		UserPrefs *[]struct {
			Component *string `json:"component,omitempty" yaml:"component,omitempty"`
			Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
		} `json:"userPrefs,omitempty" yaml:"userPrefs,omitempty"`
		Graphql *[]struct {
			Component *string `json:"component,omitempty" yaml:"component,omitempty"`
			Path      *string `json:"path,omitempty" yaml:"path,omitempty"`
			Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
		} `json:"graphql,omitempty" yaml:"graphql,omitempty"`
		Account *[]struct {
			Component *string `json:"component,omitempty" yaml:"component,omitempty"`

			// Href Href configuration for account extensions.
			Href *struct {
				External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
				Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
			} `json:"href,omitempty" yaml:"href,omitempty"`
			Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
			OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
			Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
			Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
			Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
		} `json:"account,omitempty" yaml:"account,omitempty"`
		Collaborator *[]struct {
			Component *string `json:"component,omitempty" yaml:"component,omitempty"`
			Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
		} `json:"collaborator,omitempty" yaml:"collaborator,omitempty"`
	} `json:"extensions,omitempty" yaml:"extensions,omitempty"`

	// Capabilities List of general feature capabilities.
	Capabilities *[]struct {
		// Endpoint API endpoint for the feature.
		Endpoint *string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`

		// Feature Feature identifier.
		Feature *string `json:"feature,omitempty" yaml:"feature,omitempty"`
	} `json:"capabilities,omitempty" yaml:"capabilities,omitempty"`

	// RestrictedAccess Restricted access configuration for the Meshery UI.
	RestrictedAccess *struct {
		// AllowedComponents Meshery UI component capability.
		AllowedComponents *struct {
			// Header Header component visibility settings.
			Header *struct {
				ContextSwitcher *bool `json:"contextSwitcher,omitempty" yaml:"contextSwitcher,omitempty"`
				Notifications   *bool `json:"notifications,omitempty" yaml:"notifications,omitempty"`
				Profile         *bool `json:"profile,omitempty" yaml:"profile,omitempty"`
				Settings        *bool `json:"settings,omitempty" yaml:"settings,omitempty"`
			} `json:"header,omitempty" yaml:"header,omitempty"`

			// Navigator Navigator component visibility settings.
			Navigator *struct {
				// Configuration Configuration component visibility settings.
				Configuration *struct {
					Applications *bool `json:"applications,omitempty" yaml:"applications,omitempty"`
					Designs      *bool `json:"designs,omitempty" yaml:"designs,omitempty"`
					Filters      *bool `json:"filters,omitempty" yaml:"filters,omitempty"`
				} `json:"configuration,omitempty" yaml:"configuration,omitempty"`
				Conformance *bool                   `json:"conformance,omitempty" yaml:"conformance,omitempty"`
				Dashboard   *bool                   `json:"dashboard,omitempty" yaml:"dashboard,omitempty"`
				Extensions  *bool                   `json:"extensions,omitempty" yaml:"extensions,omitempty"`
				Help        *bool                   `json:"help,omitempty" yaml:"help,omitempty"`
				Lifecycle   *map[string]interface{} `json:"lifecycle,omitempty" yaml:"lifecycle,omitempty"`
				Performance *bool                   `json:"performance,omitempty" yaml:"performance,omitempty"`
				Toggler     *bool                   `json:"toggler,omitempty" yaml:"toggler,omitempty"`
			} `json:"navigator,omitempty" yaml:"navigator,omitempty"`
		} `json:"allowedComponents,omitempty" yaml:"allowedComponents,omitempty"`
		IsMesheryUIRestricted *bool `json:"isMesheryUIRestricted,omitempty" yaml:"isMesheryUIRestricted,omitempty"`
	} `json:"restrictedAccess,omitempty" yaml:"restrictedAccess,omitempty"`
}

// CapabilityAccountExtension Account extension for the user profile area.
type CapabilityAccountExtension struct {
	Component *string `json:"component,omitempty" yaml:"component,omitempty"`

	// Href Href configuration for account extensions.
	Href *struct {
		External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
		Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
	} `json:"href,omitempty" yaml:"href,omitempty"`
	Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
	OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
	Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
	Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
	Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
}

// CapabilityAccountExtensionHref Href configuration for account extensions.
type CapabilityAccountExtensionHref struct {
	External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
	Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
}

// CapabilityCollaboratorsExtension Collaborators extension.
type CapabilityCollaboratorsExtension struct {
	Component *string `json:"component,omitempty" yaml:"component,omitempty"`
	Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
}

// CapabilityExtension Extension points for the Meshery UI and backend.
type CapabilityExtension struct {
	Navigator *[]struct {
		AllowedTo *map[string]interface{} `json:"allowedTo,omitempty" yaml:"allowedTo,omitempty"`
		Component *string                 `json:"component,omitempty" yaml:"component,omitempty"`

		// Href Href configuration for navigator extensions.
		Href *struct {
			External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
			Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
		} `json:"href,omitempty" yaml:"href,omitempty"`
		Icon            *string `json:"icon,omitempty" yaml:"icon,omitempty"`
		IsBeta          *bool   `json:"isBeta,omitempty" yaml:"isBeta,omitempty"`
		Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
		OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
		Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
		Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
		Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
	} `json:"navigator,omitempty" yaml:"navigator,omitempty"`
	UserPrefs *[]struct {
		Component *string `json:"component,omitempty" yaml:"component,omitempty"`
		Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
	} `json:"userPrefs,omitempty" yaml:"userPrefs,omitempty"`
	Graphql *[]struct {
		Component *string `json:"component,omitempty" yaml:"component,omitempty"`
		Path      *string `json:"path,omitempty" yaml:"path,omitempty"`
		Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
	} `json:"graphql,omitempty" yaml:"graphql,omitempty"`
	Account *[]struct {
		Component *string `json:"component,omitempty" yaml:"component,omitempty"`

		// Href Href configuration for account extensions.
		Href *struct {
			External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
			Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
		} `json:"href,omitempty" yaml:"href,omitempty"`
		Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
		OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
		Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
		Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
		Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
	} `json:"account,omitempty" yaml:"account,omitempty"`
	Collaborator *[]struct {
		Component *string `json:"component,omitempty" yaml:"component,omitempty"`
		Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
	} `json:"collaborator,omitempty" yaml:"collaborator,omitempty"`
}

// CapabilityGeneralCapability General capability defining a feature and its endpoint.
type CapabilityGeneralCapability struct {
	// Endpoint API endpoint for the feature.
	Endpoint *string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`

	// Feature Feature identifier.
	Feature *string `json:"feature,omitempty" yaml:"feature,omitempty"`
}

// CapabilityGraphQLExtension GraphQL backend extension.
type CapabilityGraphQLExtension struct {
	Component *string `json:"component,omitempty" yaml:"component,omitempty"`
	Path      *string `json:"path,omitempty" yaml:"path,omitempty"`
	Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
}

// CapabilityNavigatorExtension Navigator extension for the Meshery UI sidebar.
type CapabilityNavigatorExtension struct {
	AllowedTo *map[string]interface{} `json:"allowedTo,omitempty" yaml:"allowedTo,omitempty"`
	Component *string                 `json:"component,omitempty" yaml:"component,omitempty"`

	// Href Href configuration for navigator extensions.
	Href *struct {
		External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
		Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
	} `json:"href,omitempty" yaml:"href,omitempty"`
	Icon            *string `json:"icon,omitempty" yaml:"icon,omitempty"`
	IsBeta          *bool   `json:"isBeta,omitempty" yaml:"isBeta,omitempty"`
	Link            *bool   `json:"link,omitempty" yaml:"link,omitempty"`
	OnClickCallback *int    `json:"onClickCallback,omitempty" yaml:"onClickCallback,omitempty"`
	Show            *bool   `json:"show,omitempty" yaml:"show,omitempty"`
	Title           *string `json:"title,omitempty" yaml:"title,omitempty"`
	Type            *string `json:"type,omitempty" yaml:"type,omitempty"`
}

// CapabilityNavigatorExtensionHref Href configuration for navigator extensions.
type CapabilityNavigatorExtensionHref struct {
	External *bool   `json:"external,omitempty" yaml:"external,omitempty"`
	Uri      *string `json:"uri,omitempty" yaml:"uri,omitempty"`
}

// CapabilityUserPrefExtension User preferences extension.
type CapabilityUserPrefExtension struct {
	Component *string `json:"component,omitempty" yaml:"component,omitempty"`
	Type      *string `json:"type,omitempty" yaml:"type,omitempty"`
}

// Configuration Configuration component visibility settings.
type Configuration struct {
	Applications *bool `json:"applications,omitempty" yaml:"applications,omitempty"`
	Designs      *bool `json:"designs,omitempty" yaml:"designs,omitempty"`
	Filters      *bool `json:"filters,omitempty" yaml:"filters,omitempty"`
}

// DesignerComponents Designer component permission flags.
type DesignerComponents struct {
	Application *bool `json:"application,omitempty" yaml:"application,omitempty"`
	Deploy      *bool `json:"deploy,omitempty" yaml:"deploy,omitempty"`
	Design      *bool `json:"design,omitempty" yaml:"design,omitempty"`
	Filter      *bool `json:"filter,omitempty" yaml:"filter,omitempty"`
	New         *bool `json:"new,omitempty" yaml:"new,omitempty"`
	Save        *bool `json:"save,omitempty" yaml:"save,omitempty"`
	SaveAs      *bool `json:"saveAs,omitempty" yaml:"saveAs,omitempty"`
	Undeploy    *bool `json:"undeploy,omitempty" yaml:"undeploy,omitempty"`
	Validate    *bool `json:"validate,omitempty" yaml:"validate,omitempty"`
}

// HeaderComponents Header component visibility settings.
type HeaderComponents struct {
	ContextSwitcher *bool `json:"contextSwitcher,omitempty" yaml:"contextSwitcher,omitempty"`
	Notifications   *bool `json:"notifications,omitempty" yaml:"notifications,omitempty"`
	Profile         *bool `json:"profile,omitempty" yaml:"profile,omitempty"`
	Settings        *bool `json:"settings,omitempty" yaml:"settings,omitempty"`
}

// MeshMapComponentSet Component set for MeshMap (Kanvas) permissions.
type MeshMapComponentSet struct {
	// Designer Designer component permission flags.
	Designer *struct {
		Application *bool `json:"application,omitempty" yaml:"application,omitempty"`
		Deploy      *bool `json:"deploy,omitempty" yaml:"deploy,omitempty"`
		Design      *bool `json:"design,omitempty" yaml:"design,omitempty"`
		Filter      *bool `json:"filter,omitempty" yaml:"filter,omitempty"`
		New         *bool `json:"new,omitempty" yaml:"new,omitempty"`
		Save        *bool `json:"save,omitempty" yaml:"save,omitempty"`
		SaveAs      *bool `json:"saveAs,omitempty" yaml:"saveAs,omitempty"`
		Undeploy    *bool `json:"undeploy,omitempty" yaml:"undeploy,omitempty"`
		Validate    *bool `json:"validate,omitempty" yaml:"validate,omitempty"`
	} `json:"designer,omitempty" yaml:"designer,omitempty"`
	Visualizer *bool `json:"visualizer,omitempty" yaml:"visualizer,omitempty"`
}

// MesheryUICapability Meshery UI component capability.
type MesheryUICapability struct {
	// Header Header component visibility settings.
	Header *struct {
		ContextSwitcher *bool `json:"contextSwitcher,omitempty" yaml:"contextSwitcher,omitempty"`
		Notifications   *bool `json:"notifications,omitempty" yaml:"notifications,omitempty"`
		Profile         *bool `json:"profile,omitempty" yaml:"profile,omitempty"`
		Settings        *bool `json:"settings,omitempty" yaml:"settings,omitempty"`
	} `json:"header,omitempty" yaml:"header,omitempty"`

	// Navigator Navigator component visibility settings.
	Navigator *struct {
		// Configuration Configuration component visibility settings.
		Configuration *struct {
			Applications *bool `json:"applications,omitempty" yaml:"applications,omitempty"`
			Designs      *bool `json:"designs,omitempty" yaml:"designs,omitempty"`
			Filters      *bool `json:"filters,omitempty" yaml:"filters,omitempty"`
		} `json:"configuration,omitempty" yaml:"configuration,omitempty"`
		Conformance *bool                   `json:"conformance,omitempty" yaml:"conformance,omitempty"`
		Dashboard   *bool                   `json:"dashboard,omitempty" yaml:"dashboard,omitempty"`
		Extensions  *bool                   `json:"extensions,omitempty" yaml:"extensions,omitempty"`
		Help        *bool                   `json:"help,omitempty" yaml:"help,omitempty"`
		Lifecycle   *map[string]interface{} `json:"lifecycle,omitempty" yaml:"lifecycle,omitempty"`
		Performance *bool                   `json:"performance,omitempty" yaml:"performance,omitempty"`
		Toggler     *bool                   `json:"toggler,omitempty" yaml:"toggler,omitempty"`
	} `json:"navigator,omitempty" yaml:"navigator,omitempty"`
}

// NavigatorComponents Navigator component visibility settings.
type NavigatorComponents struct {
	// Configuration Configuration component visibility settings.
	Configuration *struct {
		Applications *bool `json:"applications,omitempty" yaml:"applications,omitempty"`
		Designs      *bool `json:"designs,omitempty" yaml:"designs,omitempty"`
		Filters      *bool `json:"filters,omitempty" yaml:"filters,omitempty"`
	} `json:"configuration,omitempty" yaml:"configuration,omitempty"`
	Conformance *bool                   `json:"conformance,omitempty" yaml:"conformance,omitempty"`
	Dashboard   *bool                   `json:"dashboard,omitempty" yaml:"dashboard,omitempty"`
	Extensions  *bool                   `json:"extensions,omitempty" yaml:"extensions,omitempty"`
	Help        *bool                   `json:"help,omitempty" yaml:"help,omitempty"`
	Lifecycle   *map[string]interface{} `json:"lifecycle,omitempty" yaml:"lifecycle,omitempty"`
	Performance *bool                   `json:"performance,omitempty" yaml:"performance,omitempty"`
	Toggler     *bool                   `json:"toggler,omitempty" yaml:"toggler,omitempty"`
}

// RestrictedAccess Restricted access configuration for the Meshery UI.
type RestrictedAccess struct {
	// AllowedComponents Meshery UI component capability.
	AllowedComponents *struct {
		// Header Header component visibility settings.
		Header *struct {
			ContextSwitcher *bool `json:"contextSwitcher,omitempty" yaml:"contextSwitcher,omitempty"`
			Notifications   *bool `json:"notifications,omitempty" yaml:"notifications,omitempty"`
			Profile         *bool `json:"profile,omitempty" yaml:"profile,omitempty"`
			Settings        *bool `json:"settings,omitempty" yaml:"settings,omitempty"`
		} `json:"header,omitempty" yaml:"header,omitempty"`

		// Navigator Navigator component visibility settings.
		Navigator *struct {
			// Configuration Configuration component visibility settings.
			Configuration *struct {
				Applications *bool `json:"applications,omitempty" yaml:"applications,omitempty"`
				Designs      *bool `json:"designs,omitempty" yaml:"designs,omitempty"`
				Filters      *bool `json:"filters,omitempty" yaml:"filters,omitempty"`
			} `json:"configuration,omitempty" yaml:"configuration,omitempty"`
			Conformance *bool                   `json:"conformance,omitempty" yaml:"conformance,omitempty"`
			Dashboard   *bool                   `json:"dashboard,omitempty" yaml:"dashboard,omitempty"`
			Extensions  *bool                   `json:"extensions,omitempty" yaml:"extensions,omitempty"`
			Help        *bool                   `json:"help,omitempty" yaml:"help,omitempty"`
			Lifecycle   *map[string]interface{} `json:"lifecycle,omitempty" yaml:"lifecycle,omitempty"`
			Performance *bool                   `json:"performance,omitempty" yaml:"performance,omitempty"`
			Toggler     *bool                   `json:"toggler,omitempty" yaml:"toggler,omitempty"`
		} `json:"navigator,omitempty" yaml:"navigator,omitempty"`
	} `json:"allowedComponents,omitempty" yaml:"allowedComponents,omitempty"`
	IsMesheryUIRestricted *bool `json:"isMesheryUIRestricted,omitempty" yaml:"isMesheryUIRestricted,omitempty"`
}
