// Package credential provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package credential

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/meshery/schemas/models/core"
)

// Credential Meshery Credentials store sensitive information such as API keys, tokens, and passwords used by connections to external systems.
type Credential struct {
	// Id Unique identifier for the credential.
	Id uuid.UUID `db:"id" json:"id" yaml:"id"`

	// Name Human-readable name for the credential.
	Name string `db:"name" json:"name" yaml:"name"`

	// UserId UUID of the user who owns this credential.
	UserId *uuid.UUID `db:"user_id" json:"user_id,omitempty" yaml:"user_id,omitempty"`

	// Type Credential type (e.g. token, basic, AWS).
	Type string `db:"type" json:"type" yaml:"type"`

	// Secret Key-value pairs containing the sensitive credential data.
	Secret core.Map `db:"secret" json:"secret,omitempty" yaml:"secret,omitempty"`

	// CreatedAt Timestamp when the credential was created.
	CreatedAt time.Time `db:"created_at" json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// UpdatedAt Timestamp when the credential was last updated.
	UpdatedAt time.Time `db:"updated_at" json:"updated_at,omitempty" yaml:"updated_at,omitempty"`

	// DeletedAt Timestamp when the credential was soft-deleted.
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
}

// CredentialPage A paginated list of credentials.
type CredentialPage struct {
	Credentials []Credential `json:"credentials" yaml:"credentials"`

	// TotalCount Total number of credentials across all pages.
	TotalCount int `json:"total_count" yaml:"total_count"`

	// Page Current page number (zero-based).
	Page int `json:"page" yaml:"page"`

	// PageSize Number of credentials per page.
	PageSize int `json:"page_size" yaml:"page_size"`
}

// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type Id = uuid.UUID

// Order defines model for order.
type Order = string

// Page defines model for page.
type Page = string

// Pagesize defines model for pagesize.
type Pagesize = string

// Search defines model for search.
type Search = string
