// Package schedule provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schedule

import (
	"time"

	"github.com/gofrs/uuid"
)

// Schedule A schedule defines a recurring cron-based trigger for performance tests or other automated tasks.
type Schedule struct {
	// Id Unique identifier for the schedule.
	Id uuid.UUID `db:"id" json:"id" yaml:"id"`

	// Name Human-readable name for the schedule.
	Name string `db:"name" json:"name" yaml:"name"`

	// UserId UUID of the user who owns this schedule.
	UserId uuid.UUID `db:"user_id" json:"user_id" yaml:"user_id"`

	// CronExpression Cron expression defining the schedule's recurrence (e.g. "0 0 * * *" for daily at midnight).
	CronExpression string `db:"cron_expression" json:"cron_expression" yaml:"cron_expression"`

	// CreatedAt Timestamp when the schedule was created.
	CreatedAt time.Time `db:"created_at" json:"created_at" yaml:"created_at"`

	// UpdatedAt Timestamp when the schedule was last updated.
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" yaml:"updated_at"`
}

// SchedulePage A paginated list of schedules.
type SchedulePage struct {
	// Page Current page number (zero-based).
	Page int `json:"page" yaml:"page"`

	// PageSize Number of schedules per page.
	PageSize int `json:"page_size" yaml:"page_size"`

	// TotalCount Total number of schedules across all pages.
	TotalCount int        `json:"total_count" yaml:"total_count"`
	Schedules  []Schedule `json:"schedules" yaml:"schedules"`
}

// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type Id = uuid.UUID

// Order defines model for order.
type Order = string

// Page defines model for page.
type Page = string

// Pagesize defines model for pagesize.
type Pagesize = string

// Search defines model for search.
type Search = string
